### ISSUE TITLE
监听华为蓝牙是否打开

### ISSUE THREAD

**Issue by NightRannie** [laoeg/Ble#3]
当我使用 Ble.getInstance().enabled()后。华为会弹出一个打开蓝牙确认框。vivo手机直接打开。但都接受不到回调。请问执行Ble.getInstance().enabled()后需要怎么操作

**Comment by NightRannie** [comment]
`     

     void onBluetoothOn() {
       print('打开蓝牙');
       int seconds = 0;
    Timer.periodic(Duration(seconds: 1), (timer) async {
      //callback function
      //  目前用了一个定时器去监听蓝牙状态。但是不能确定用户是否点的false
      bool open = await checkMobileOpenBlueTooth();
      print(open);
      print("open-------");
      seconds++;
      if (open) {
        Future.delayed(Duration(seconds: 2), () {
          startScan(_context, mac, password, lockAction);
        });
        timer.cancel(); // 取消定时器
      } else {
        if (seconds > 5) {
          timer.cancel();
          if (errorFn != null) {
            errorFn();
          }
        }
      }
    });
  }`

**Comment by NightRannie** [comment]
目前用了一个定时器去监听蓝牙状态。但是不能确定用户是否点的取消

**Comment by NightRannie** [comment]
`   


     Ble.getInstance().initEvent();
     Ble.getInstance().setDeviceListener(ScanLockToOpen());
     bool open = await checkMobileOpenBlueTooth();
    if (!open) {
      FormUtils.showOkCancelAlertDialogModel(context, message: '寓小猪需要打开蓝牙连接门锁',
          confirm: (bool result) {
        print(result);
        print("result------------");
        if (result) {
          Ble.getInstance().enabled();
        } else {
          if (errorFn != null) {
            errorFn();
          }
        }
      });
    } else {
      // beginFoundDevice();
   
      Ble.getInstance().startScanBluetooth;
    }`

**Comment by laoge-lol** [comment]
监听：onBluetoothOn()，onBluetoothOff()
